name: Deploy MultiK8s
on:
  push:
    branches:
      - main
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker build -t vvb07/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true vvb07/react-test npm test
 
      - name: Set Identity Provider
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/985173054136/locations/global/workloadIdentityPools/github/providers/my-repo-v2"
          project_id: "${{ secrets.GKE_PROJECT_ID }}"
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ secrets.GKE_PROJECT_ID }}"
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "${{ secrets.GKE_CLUSTER_NAME }}"
          location: "${{ secrets.GKE_CLUSTER_LOCATION }}"
          project_id: "${{ secrets.GKE_PROJECT_ID }}"
 
      - name: Build
        run: |-
          docker build -t vvb07/multi-client-k8s:latest -t vvb07/multi-client-k8s:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t vvb07/multi-server-k8s:latest -t vvb07/multi-server-k8s:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t vvb07/multi-worker-k8s:latest -t vvb07/multi-worker-k8s:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push vvb07/multi-client-k8s:latest
          docker push vvb07/multi-server-k8s:latest
          docker push vvb07/multi-worker-k8s:latest
 
          docker push vvb07/multi-client-k8s:${{ env.SHA }}
          docker push vvb07/multi-server-k8s:${{ env.SHA }}
          docker push vvb07/multi-worker-k8s:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=vvb07/multi-server-k8s:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=vvb07/multi-client-k8s:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=vvb07/multi-worker-k8s:${{ env.SHA }}